stages:
  - build
  - test
  - deploy

variables:
  DOTNET_VERSION: "10.0"
  NODE_VERSION: "20"

# API
build:api:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:10.0
  script:
    - cd api/VitalSyncAPI
    - dotnet restore
    - dotnet build -c Release --no-restore
  only:
    - master
    - merge_requests

# AI SERVICE
build:ai-service:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:10.0
  script:
    - cd ai-service/VitalSyncAI
    - dotnet restore
    - dotnet build -c Release --no-restore
  only:
    - master
    - merge_requests

# FRONT
build:frontend:
  stage: build
  image: node:20-alpine
  variables:
    NG_BUILD_PRERENDER: "false"
  script:
    - cd front/vitalsync-front
    - npm ci
    - npx ng build --configuration=production
  only:
    - master
    - merge_requests

# TEST API
test:api:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:10.0
  script:
    - cd api/VitalSyncAPI
    - dotnet test --no-build -c Release
  only:
    - master
    - merge_requests

# DEPLOY
deploy:production:
  stage: deploy
  tags:
    - homeserver
  script:
    - git config --global --add safe.directory /home/arthur.cruz/Documents/Projetos/VitalSync
    - cd /home/arthur.cruz/Documents/Projetos/VitalSync
    - git reset --hard origin/master
    - docker compose up --build -d
  only:
    - master
  environment:
    name: production