services:
  api:
    build:
      context: ./api/VitalSyncAPI
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=vitalsync;Username=${DB_USER};Password=${DB_PASSWORD}
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=vitalsync
      - Jwt__Audience=vitalsync
      - Jwt__ExpiresInMinutes=60
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: vitalsync
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./front/vitalsync-front
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./front/vitalsync-front/src:/app/src
      - ./front/vitalsync-front/public:/app/public
    depends_on:
      - api

volumes:
  pgdata:
