// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VitalSyncAPI.Infrastructure.Data;

#nullable disable

namespace VitalSyncAPI.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260524052314_AddAlertsV2")]
    partial class AddAlertsV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VitalSyncAPI.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<Guid>("HealthRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("health_record_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<int>("MetricTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("metric_type_id");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("triggered_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("HealthRecordId");

                    b.HasIndex("MetricTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("alerts");
                });

            modelBuilder.Entity("VitalSyncAPI.Domain.Entities.HealthCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("health_conditions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hipertensão"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Diabetes tipo 1"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Diabetes tipo 2"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Obesidade"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Doença cardíaca"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Asma"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Doença renal crônica"
                        });
                });

            modelBuilder.Entity("VitalSyncAPI.Domain.Entities.HealthRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measured_at");

                    b.Property<int>("MetricTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("metric_type_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("MetricTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("health_records");
                });

            modelBuilder.Entity("VitalSyncAPI.Domain.Entities.MetricType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<double?>("MaxNormal")
                        .HasColumnType("double precision")
                        .HasColumnName("max_normal");

                    b.Property<double?>("MinNormal")
                        .HasColumnType("double precision")
                        .HasColumnName("min_normal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.ToTable("metric_types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "blood-pressure",
                            MaxNormal = 120.0,
                            MinNormal = 90.0,
                            Name = "Pressão Sistólica",
                            SortOrder = 1,
                            Unit = "mmHg"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "blood-pressure",
                            MaxNormal = 80.0,
                            MinNormal = 60.0,
                            Name = "Pressão Diastólica",
                            SortOrder = 2,
                            Unit = "mmHg"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "droplet",
                            MaxNormal = 99.0,
                            MinNormal = 70.0,
                            Name = "Glicemia",
                            SortOrder = 3,
                            Unit = "mg/dL"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "heart-pulse",
                            MaxNormal = 100.0,
                            MinNormal = 60.0,
                            Name = "Frequência Cardíaca",
                            SortOrder = 4,
                            Unit = "bpm"
                        },
                        new
                        {
                            Id = 5,
                            Icon = "scale",
                            Name = "Peso",
                            SortOrder = 5,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 6,
                            Icon = "lungs",
                            MaxNormal = 100.0,
                            MinNormal = 95.0,
                            Name = "SpO2",
                            SortOrder = 6,
                            Unit = "%"
                        },
                        new
                        {
                            Id = 7,
                            Icon = "moon",
                            MaxNormal = 9.0,
                            MinNormal = 7.0,
                            Name = "Sono",
                            SortOrder = 7,
                            Unit = "h"
                        },
                        new
                        {
                            Id = 8,
                            Icon = "smile",
                            Name = "Humor",
                            SortOrder = 8,
                            Unit = "1-5"
                        });
                });

            modelBuilder.Entity("VitalSyncAPI.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birthdate");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("VitalSyncAPI.Domain.Entities.UserCondition", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("ConditionId")
                        .HasColumnType("integer")
                        .HasColumnName("condition_id");

                    b.HasKey("UserId", "ConditionId");

                    b.HasIndex("ConditionId");

                    b.ToTable("user_conditions");
                });

            modelBuilder.Entity("VitalSyncAPI.Domain.Entities.Alert", b =>
                {
                    b.HasOne("VitalSyncAPI.Domain.Entities.HealthRecord", "HealthRecord")
                        .WithMany()
                        .HasForeignKey("HealthRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VitalSyncAPI.Domain.Entities.MetricType", "MetricType")
                        .WithMany()
                        .HasForeignKey("MetricTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VitalSyncAPI.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthRecord");

                    b.Navigation("MetricType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VitalSyncAPI.Domain.Entities.HealthRecord", b =>
                {
                    b.HasOne("VitalSyncAPI.Domain.Entities.MetricType", "MetricType")
                        .WithMany("Records")
                        .HasForeignKey("MetricTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VitalSyncAPI.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetricType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VitalSyncAPI.Domain.Entities.UserCondition", b =>
                {
                    b.HasOne("VitalSyncAPI.Domain.Entities.HealthCondition", "Condition")
                        .WithMany()
                        .HasForeignKey("ConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VitalSyncAPI.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VitalSyncAPI.Domain.Entities.MetricType", b =>
                {
                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
