// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VitalSyncAPI.Infrastructure.Data;

#nullable disable

namespace VitalSyncAPI.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260605204514_AddSOP")]
    partial class AddSOP
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VitalSyncAPI.Domain.Entities.AIInsight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Disclaimer")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("disclaimer");

                    b.Property<Guid?>("HealthRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("health_record_id");

                    b.Property<string>("Insights")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("insights");

                    b.Property<string>("OverallAssessment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("overall_assessment");

                    b.Property<string>("Tips")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tips");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("HealthRecordId");

                    b.HasIndex("UserId");

                    b.ToTable("ai_insights");
                });

            modelBuilder.Entity("VitalSyncAPI.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<Guid>("HealthRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("health_record_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<int>("MetricTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("metric_type_id");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("triggered_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("HealthRecordId");

                    b.HasIndex("MetricTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("alerts");
                });

            modelBuilder.Entity("VitalSyncAPI.Domain.Entities.BodyMetrics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BMI")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("bmi");

                    b.Property<decimal>("BMR")
                        .HasColumnType("decimal(7,2)")
                        .HasColumnName("bmr");

                    b.Property<decimal>("CalorieGoal")
                        .HasColumnType("decimal(7,2)")
                        .HasColumnName("calorie_goal");

                    b.Property<decimal>("CarbsGoalG")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("carbs_goal_g");

                    b.Property<decimal>("FatGoalG")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("fat_goal_g");

                    b.Property<decimal>("IdealWeightMaxKg")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("ideal_weight_max_kg");

                    b.Property<decimal>("IdealWeightMinKg")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("ideal_weight_min_kg");

                    b.Property<decimal>("ProteinGoalG")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("protein_goal_g");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<decimal>("TDEE")
                        .HasColumnType("decimal(7,2)")
                        .HasColumnName("tdee");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("body_metrics");
                });

            modelBuilder.Entity("VitalSyncAPI.Domain.Entities.HealthCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("health_conditions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hipertensão"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Diabetes tipo 1"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Diabetes tipo 2"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Pré-diabetes"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Obesidade"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Doença cardíaca"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Colesterol alto"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Hipotireoidismo"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Hipertireoidismo"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Asma"
                        },
                        new
                        {
                            Id = 11,
                            Name = "DPOC"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Doença renal crônica"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Apneia do sono"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Ansiedade"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Depressão"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Fibromialgia"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Síndrome do Ovário Policístico (SOP)"
                        });
                });

            modelBuilder.Entity("VitalSyncAPI.Domain.Entities.HealthRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measured_at");

                    b.Property<int>("MetricTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("metric_type_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("MetricTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("health_records");
                });

            modelBuilder.Entity("VitalSyncAPI.Domain.Entities.MetricType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<double?>("MaxNormal")
                        .HasColumnType("double precision")
                        .HasColumnName("max_normal");

                    b.Property<double?>("MinNormal")
                        .HasColumnType("double precision")
                        .HasColumnName("min_normal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.ToTable("metric_types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "blood-pressure",
                            MaxNormal = 120.0,
                            MinNormal = 90.0,
                            Name = "Pressão Sistólica",
                            SortOrder = 1,
                            Unit = "mmHg"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "blood-pressure",
                            MaxNormal = 80.0,
                            MinNormal = 60.0,
                            Name = "Pressão Diastólica",
                            SortOrder = 2,
                            Unit = "mmHg"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "droplet",
                            MaxNormal = 99.0,
                            MinNormal = 70.0,
                            Name = "Glicemia em jejum",
                            SortOrder = 3,
                            Unit = "mg/dL"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "heart-pulse",
                            MaxNormal = 100.0,
                            MinNormal = 60.0,
                            Name = "Frequência Cardíaca",
                            SortOrder = 4,
                            Unit = "bpm"
                        },
                        new
                        {
                            Id = 5,
                            Icon = "scale",
                            Name = "Peso",
                            SortOrder = 5,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 6,
                            Icon = "lungs",
                            MaxNormal = 100.0,
                            MinNormal = 95.0,
                            Name = "SpO2",
                            SortOrder = 6,
                            Unit = "%"
                        },
                        new
                        {
                            Id = 7,
                            Icon = "moon",
                            MaxNormal = 9.0,
                            MinNormal = 7.0,
                            Name = "Sono",
                            SortOrder = 7,
                            Unit = "h"
                        },
                        new
                        {
                            Id = 8,
                            Icon = "smile",
                            Name = "Humor",
                            SortOrder = 8,
                            Unit = "1-5"
                        },
                        new
                        {
                            Id = 9,
                            Icon = "thermometer",
                            MaxNormal = 37.5,
                            MinNormal = 36.0,
                            Name = "Temperatura Corporal",
                            SortOrder = 9,
                            Unit = "°C"
                        },
                        new
                        {
                            Id = 10,
                            Icon = "droplet",
                            MaxNormal = 140.0,
                            Name = "Glicemia Pós-prandial",
                            SortOrder = 10,
                            Unit = "mg/dL"
                        },
                        new
                        {
                            Id = 11,
                            Icon = "footsteps",
                            MinNormal = 5000.0,
                            Name = "Passos Diários",
                            SortOrder = 11,
                            Unit = "passos"
                        },
                        new
                        {
                            Id = 12,
                            Icon = "brain",
                            MaxNormal = 4.0,
                            Name = "Nível de Estresse",
                            SortOrder = 12,
                            Unit = "1-10"
                        });
                });

            modelBuilder.Entity("VitalSyncAPI.Domain.Entities.NutritionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CaloriesKcal")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("calories_kcal");

                    b.Property<decimal>("CarbsG")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("carbs_g");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("FatG")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("fat_g");

                    b.Property<string>("FoodDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("food_description");

                    b.Property<int>("MealType")
                        .HasColumnType("integer")
                        .HasColumnName("meal_type");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measured_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("notes");

                    b.Property<decimal>("ProteinG")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("protein_g");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("nutrition_records");
                });

            modelBuilder.Entity("VitalSyncAPI.Domain.Entities.PersonalRange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at");

                    b.Property<decimal>("MaxNormal")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("max_normal");

                    b.Property<int>("Method")
                        .HasColumnType("integer")
                        .HasColumnName("method");

                    b.Property<int>("MetricTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("metric_type_id");

                    b.Property<decimal>("MinNormal")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("min_normal");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("MetricTypeId");

                    b.HasIndex("UserId", "MetricTypeId")
                        .IsUnique();

                    b.ToTable("personal_ranges");
                });

            modelBuilder.Entity("VitalSyncAPI.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birthdate");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("VitalSyncAPI.Domain.Entities.UserCondition", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("ConditionId")
                        .HasColumnType("integer")
                        .HasColumnName("condition_id");

                    b.HasKey("UserId", "ConditionId");

                    b.HasIndex("ConditionId");

                    b.ToTable("user_conditions");
                });

            modelBuilder.Entity("VitalSyncAPI.Domain.Entities.UserMedication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("MedicationClass")
                        .HasColumnType("integer")
                        .HasColumnName("medication_class");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("notes");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_medications");
                });

            modelBuilder.Entity("VitalSyncAPI.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActivityLevel")
                        .HasColumnType("integer")
                        .HasColumnName("activity_level");

                    b.Property<decimal?>("BodyFatPercent")
                        .HasColumnType("numeric")
                        .HasColumnName("body_fat_percent");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Goal")
                        .HasColumnType("integer")
                        .HasColumnName("goal");

                    b.Property<decimal>("HabitualSleepHours")
                        .HasColumnType("numeric")
                        .HasColumnName("habitual_sleep_hours");

                    b.Property<decimal>("HeightCm")
                        .HasColumnType("numeric")
                        .HasColumnName("height_cm");

                    b.Property<int>("HoursSeated")
                        .HasColumnType("integer")
                        .HasColumnName("hours_seated_per_day");

                    b.Property<int>("SleepQuality")
                        .HasColumnType("integer")
                        .HasColumnName("sleep_quality");

                    b.Property<decimal?>("TargetWeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("target_weight_kg");

                    b.Property<int>("TrainingFrequencyDays")
                        .HasColumnType("integer")
                        .HasColumnName("training_frequency_days");

                    b.Property<string>("TrainingTypes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("training_types");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<decimal?>("WaistCircumferenceCm")
                        .HasColumnType("numeric")
                        .HasColumnName("waist_circumference_cm");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_profiles");
                });

            modelBuilder.Entity("VitalSyncAPI.Domain.Entities.AIInsight", b =>
                {
                    b.HasOne("VitalSyncAPI.Domain.Entities.HealthRecord", "HealthRecord")
                        .WithMany("AIInsight")
                        .HasForeignKey("HealthRecordId");

                    b.HasOne("VitalSyncAPI.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthRecord");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VitalSyncAPI.Domain.Entities.Alert", b =>
                {
                    b.HasOne("VitalSyncAPI.Domain.Entities.HealthRecord", "HealthRecord")
                        .WithMany()
                        .HasForeignKey("HealthRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VitalSyncAPI.Domain.Entities.MetricType", "MetricType")
                        .WithMany()
                        .HasForeignKey("MetricTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VitalSyncAPI.Domain.Entities.User", "User")
                        .WithMany("Alerts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthRecord");

                    b.Navigation("MetricType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VitalSyncAPI.Domain.Entities.BodyMetrics", b =>
                {
                    b.HasOne("VitalSyncAPI.Domain.Entities.User", "User")
                        .WithMany("BodyMetrics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VitalSyncAPI.Domain.Entities.HealthRecord", b =>
                {
                    b.HasOne("VitalSyncAPI.Domain.Entities.MetricType", "MetricType")
                        .WithMany("Records")
                        .HasForeignKey("MetricTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VitalSyncAPI.Domain.Entities.User", "User")
                        .WithMany("HealthRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetricType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VitalSyncAPI.Domain.Entities.NutritionRecord", b =>
                {
                    b.HasOne("VitalSyncAPI.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VitalSyncAPI.Domain.Entities.PersonalRange", b =>
                {
                    b.HasOne("VitalSyncAPI.Domain.Entities.MetricType", "MetricType")
                        .WithMany()
                        .HasForeignKey("MetricTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VitalSyncAPI.Domain.Entities.User", "User")
                        .WithMany("PersonalRanges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetricType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VitalSyncAPI.Domain.Entities.UserCondition", b =>
                {
                    b.HasOne("VitalSyncAPI.Domain.Entities.HealthCondition", "Condition")
                        .WithMany()
                        .HasForeignKey("ConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VitalSyncAPI.Domain.Entities.User", "User")
                        .WithMany("Conditions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VitalSyncAPI.Domain.Entities.UserMedication", b =>
                {
                    b.HasOne("VitalSyncAPI.Domain.Entities.User", "User")
                        .WithMany("Medications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VitalSyncAPI.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("VitalSyncAPI.Domain.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("VitalSyncAPI.Domain.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VitalSyncAPI.Domain.Entities.HealthRecord", b =>
                {
                    b.Navigation("AIInsight");
                });

            modelBuilder.Entity("VitalSyncAPI.Domain.Entities.MetricType", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("VitalSyncAPI.Domain.Entities.User", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("BodyMetrics");

                    b.Navigation("Conditions");

                    b.Navigation("HealthRecords");

                    b.Navigation("Medications");

                    b.Navigation("PersonalRanges");

                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
